### ISSUE TITLE
Singleton shown as false in __FEDERATION__ object

### ISSUE THREAD

**Issue by idonava** [idonava/base-mf-app#1]
The React dependency is set to `singleton: true` in MF, but in the __FEDERATION__ object, it appears as `singleton: false`.
MF Host `react` singleton set:
https://github.com/idonava/base-mf-app/blob/e90d51c2ca4d9dd4c42d2eff68ed9b6616fe540f/apps/host/rsbuild.config.ts#L68-L71

__FEDERATION__ snapshot
![image](https://github.com/user-attachments/assets/b809ea4e-f26e-4585-9310-e55f348a9bf1)

**Comment by 2heal1** [comment]
Rspack not pass through the config to runtime @ahabhgk

**Comment by idonava** [comment]
Thanks for the quick fix!
