### ISSUE TITLE
MF adds unrequested caret (^) to shareConfig package requiredVersion

### ISSUE THREAD

**Issue by idonava** [idonava/base-mf-app#3]
1. In `mfe-remote-1-child-1` package.json we set `external-package-version-display` to `1.1.0` (without ^):
https://github.com/idonava/base-mf-app/blob/63cfc5e42dc33f779fc262f6094e077d3f4cc5ad/apps/mfe-remote-1/remotes/mfe-remote-1-child-1/package.json#L15
2. In `mfe-remote-1-child-1` rsbuild.config.ts we set the `requiredVersion` of `external-package-version-display` to the version in the package.json (1.1.0, without ^) in the shared scope.
https://github.com/idonava/base-mf-app/blob/main/apps/mfe-remote-1/remotes/mfe-remote-1-child-1/rsbuild.config.ts#L38-L40

In the __FEDERATION__ object, the  `external-package-version-display` requiredVersion in `mfe-remote-1-child-1` MFE is **"^1.1.0"** instead of **"1.1.0"** (added unnecessary ^)
![image](https://github.com/user-attachments/assets/70b23523-f508-4011-846d-d2f83be3f5cf)

**Comment by 2heal1** [comment]
It will be fixed in this pr https://github.com/web-infra-dev/rspack/pull/7408

**Comment by idonava** [comment]
Thanks!
